platform :ios, '10.0'
use_frameworks!
target "DotaAsker" do
	pod 'AFNetworking', '~> 3.1.0'
	pod 'Realm'
	pod 'ReactiveObjC'
	pod 'libextobjc', '~> 0.4.1'
	pod 'TTGSnackbar', '~> 1.4.0'
	pod 'Charts', '~> 3.0.1'
end
