//
//  AZButton.h
//  DotaAsker
//
//  Created by Zykis on 26/11/2016.
//  Copyright © 2016 Zykis. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//

#import <UIKit/UIKit.h>



@interface PCGradient : NSObject

@property (nonatomic, readonly) CGGradientRef CGGradient NS_RETURNS_INNER_POINTER;

+ (instancetype)gradientWithColors: (NSArray<UIColor*>*)colors locations: (const CGFloat*)locations;
+ (instancetype)gradientWithStartingColor: (UIColor*)startingColor endingColor: (UIColor*)endingColor;

@end



@interface NSShadow (PaintCodeAdditions)

+ (instancetype)shadowWithColor: (UIColor*)color offset: (CGSize)offset blurRadius: (CGFloat)blurRadius;

- (void)set;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end



typedef enum : NSInteger
{
    AZButtonResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    AZButtonResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    AZButtonResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    AZButtonResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

} AZButtonResizingBehavior;

extern CGRect AZButtonResizingBehaviorApply(AZButtonResizingBehavior behavior, CGRect rect, CGRect target);


@interface AZButton : NSObject

// Colors
+ (UIColor*)color;
+ (UIColor*)gradientColor;

// Gradients
+ (PCGradient*)gradient;

// Shadows
+ (NSShadow*)shadow;

//// In Trial version of PaintCode, the code generation is limited to 3 canvases.

// Drawing Methods
+ (void)drawCanvas1WithIcon: (UIImage*)icon caption: (NSString*)caption rect: (CGRect)rect;
+ (void)drawCanvas1WithFrame: (CGRect)targetFrame resizing: (AZButtonResizingBehavior)resizing icon: (UIImage*)icon caption: (NSString*)caption rect: (CGRect)rect;

@end
