//
//  PressButtonStyleKit.h
//  DotaAsker
//
//  Created by Zykis on 29/11/2016.
//  Copyright © 2016 Zykis. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//

#import <UIKit/UIKit.h>



@interface PCGradient : NSObject

@property (nonatomic, readonly) CGGradientRef CGGradient NS_RETURNS_INNER_POINTER;

+ (instancetype)gradientWithColors: (NSArray<UIColor*>*)colors locations: (const CGFloat*)locations;
+ (instancetype)gradientWithStartingColor: (UIColor*)startingColor endingColor: (UIColor*)endingColor;

@end



@interface NSShadow (PaintCodeAdditions)

+ (instancetype)shadowWithColor: (UIColor*)color offset: (CGSize)offset blurRadius: (CGFloat)blurRadius;

- (void)set;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end



typedef enum : NSInteger
{
    PressButtonStyleKitResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    PressButtonStyleKitResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    PressButtonStyleKitResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    PressButtonStyleKitResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

} PressButtonStyleKitResizingBehavior;

extern CGRect PressButtonStyleKitResizingBehaviorApply(PressButtonStyleKitResizingBehavior behavior, CGRect rect, CGRect target);


@interface PressButtonStyleKit : NSObject

// Colors
+ (UIColor*)greenGradientColor;
+ (UIColor*)blackGradientColor;

// Gradients
+ (PCGradient*)gradient;

// Shadows
+ (NSShadow*)shadow;

//// In Trial version of PaintCode, the code generation is limited to 3 canvases.

// Drawing Methods
+ (void)drawButtonWithRect: (CGRect)rect;
+ (void)drawButtonWithFrame: (CGRect)targetFrame resizing: (PressButtonStyleKitResizingBehavior)resizing rect: (CGRect)rect;
+ (void)drawCanvas1;
+ (void)drawCanvas1WithFrame: (CGRect)targetFrame resizing: (PressButtonStyleKitResizingBehavior)resizing;

@end
